<a href="https://colab.research.google.com/github/Loelama36/Project_1_Computing_Errors/blob/main/Groupproject4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project Module 4: Gauss-Jordan Elimination

<strong>Sunil Lama<br>
Jacob Mantooth<br>
Puran Subedi<br>
Riwaz Gyawali<br>
Instructor: Dr. Nicholas Jacob<br>
Numerical Analysis
<strong>

Gauss-Jordan Method is a method in solving linear equations in the form of 
$$
\left\{
\begin{align}
a_{1,1} x_1 +&\dots a_{1,n} x_n = y_1\\
&\vdots\\
a_{n,1}x_1+&\dots a_{n,n} x_n = y_n
\end{align}
\right.
$$


## Part 1. Define functions for swapping rows, adding rows and multiplying by a constant

Our first assigment was to define a function that can swap rows and multiple a row by a constant then add it to another row 

In [ ]:
import numpy as np
import math

#Example of a Matrix that I messed around with
A = np.array([[5,2,3],[2,3,4]])


# First I defined swapping rows. My function is first you pick the martix you want, then you pick the two rows in that martix that you want to swap.
def swap(matrix,row,row2):
  matrix[[row, row2]] = matrix[[row2, row]]
  return matrix
# Now i will define adding rows.First you want to pick your martix then, pick the two function you want to add. just testing here!
#def test(matrix,row,row2):
  #matrix[[row2]]=matrix[[row]]+matrix[[row2]]
  #return matrix

# I will now define multiplying a row by a contants and adding it to a row. row2 is the one you want to change and row is the row that is get multiplied by the contant. martix is just the martix that the two rows are in
def add(matrix,row2,row,contant):
  newrow=matrix[row2,:]+contant*matrix[row,:]
  newMatrix = []
  for i in range(len(matrix)):
    if i != row2:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(newrow)
  return np.array(newMatrix)

# Finally i will define a function to get a leading one. row is the row you want to get the leading zero in and column being coloum of the number you want to have the leading zero. say i want a a leading zero in A[1,1] you would put 1 for row one and 1 for column 1.  
def leadone(matrix,row,column):
  newrow=matrix[row,:]/matrix[row,column]
  newMatrix = []
  for i in range(len(matrix)):
    if i != row:
      newMatrix.append(matrix[i,:])
    else:
      newMatrix.append(newrow)
  return np.array(newMatrix)

## Part 2. Preforming Gauss-Jordan method on a system of at least three equations and three unknowns

The system of at least three equations and three unknows that we picked is the following 
$$
\begin{align}
-5x -4y + 5z &= 12\\
-10x + 4y -6z &= 52\\
20x + 4y + 2z &= -100\\
\end{align}
$$

The np.array looks like this 

In [ ]:
B = np.array([[-5,-4,5,12],[-10,4,-6,52],[20,4,2,-100]])
B

array([[  -5,   -4,    5,   12],
       [ -10,    4,   -6,   52],
       [  20,    4,    2, -100]])

We will be sloving the equation we picked using the fuction that we defined at the beganning

First we will multiple row 1 by -2 and add it to row 2

In [ ]:
B=add(B,1,0,-2)
B

array([[  -5,   -4,    5,   12],
       [   0,   12,  -16,   28],
       [  20,    4,    2, -100]])

Next we will multiple row 1 by 4 and add it to row 3

In [ ]:
B=add(B,2,0,4)
B

array([[ -5,  -4,   5,  12],
       [  0,  12, -16,  28],
       [  0, -12,  22, -52]])

Now we will multiple row 2 by 1 and add it to row 3

In [ ]:
B=add(B,2,1,1)
B

array([[ -5,  -4,   5,  12],
       [  0,  12, -16,  28],
       [  0,   0,   6, -24]])

we will now get a leading one in row 2

In [ ]:
B=leadone(B,1,1)
B

array([[ -5.        ,  -4.        ,   5.        ,  12.        ],
       [  0.        ,   1.        ,  -1.33333333,   2.33333333],
       [  0.        ,   0.        ,   6.        , -24.        ]])

We will multiple row 2 by 4 and add it to row 1

In [ ]:
B=add(B,0,1,4)
B

array([[ -5.        ,   0.        ,  -0.33333333,  21.33333333],
       [  0.        ,   1.        ,  -1.33333333,   2.33333333],
       [  0.        ,   0.        ,   6.        , -24.        ]])

opps forgot the leading one in row one, guess ill do it now

In [ ]:
B=leadone(B,0,0)
B

array([[  1.        ,  -0.        ,   0.06666667,  -4.26666667],
       [  0.        ,   1.        ,  -1.33333333,   2.33333333],
       [  0.        ,   0.        ,   6.        , -24.        ]])

We will now need a leading zero in row 3

In [ ]:
B=leadone(B,2,2)
B

array([[ 1.        , -0.        ,  0.06666667, -4.26666667],
       [ 0.        ,  1.        , -1.33333333,  2.33333333],
       [ 0.        ,  0.        ,  1.        , -4.        ]])

We now will be add row 3 multiple by -B[1,2] to row 2

In [ ]:
B=add(B,1,2,-B[1,2])
B

array([[ 1.        , -0.        ,  0.06666667, -4.26666667],
       [ 0.        ,  1.        ,  0.        , -3.        ],
       [ 0.        ,  0.        ,  1.        , -4.        ]])

Finally we will multiple row 3 by -B[0,2] and adding it to row 1

In [ ]:
B=add(B,0,2,-B[0,2])
B

array([[ 1., -0.,  0., -4.],
       [ 0.,  1.,  0., -3.],
       [ 0.,  0.,  1., -4.]])

As you can see the functions that we defined at the beginning worked pretty well and it turns out our problem did have real number solutions. 
\begin{align}
x=-4, y=-3, and\ z=-4
\end{align}

## Part 3. Creating an algorithm for solving a systems of equations following the Gauss-Jordan elimination method and applying it to our system.

In [ ]:
#my gaussJordan function using functions that we created at the beganning 
def gaussJordan(matrix):
  newMatrix = matrix
  for pivot in range(len(matrix)):
    newMatrix = leadone(newMatrix,pivot,pivot)
    for column in range(0,pivot):
      newMatrix = add(newMatrix,column,pivot,-newMatrix[column,pivot])
    for column in range(pivot+1,len(matrix)):
        newMatrix = add(newMatrix,column,pivot,-newMatrix[column,pivot])
  return newMatrix
# What this does is try to get a leading one the then turn everything else in that column into zeroes then goes to the next column and repeats 

We will now be using our Guass-Jordan fuction to see if we are right

In [ ]:
gaussJordan(B)

array([[ 1.,  0.,  0., -4.],
       [ 0.,  1.,  0., -3.],
       [ 0.,  0.,  1., -4.]])

Looks like our Gauss-Jordan function and us got the same answer!

## Part 4 Report 

a) First of all, we have imported numpy. After that we made an array for the matrix. Our array is 3*3 array. Since, we are going to need the rows and column in this program, we define the rows and colums and then the function for swapping it. As this method will have lot of swapping of rows and column.After this step we have multiplied our matrix by a constant. In this step we have to make sure that we are trying to change one row and multiply the first row by our constant. Finally, we define the function where we get leading one in a row

On the second part of our code block we have 3 different equations where we will perform the Gauss-Jordan process. Using the np.arrary we seperate the constants that we are going to do the operation on and then we put it into array or the matrix. we then used Gauss-Jordan to find the answers 
In the last part of segment of our code,where we have defined our gauss-jordan algorithm we have defined it at first then we put it into a new value as we will be using this value inorder to perform loop.Using the for loops we finally get the answer in the row-echelon form.


b) We will now be discussing the limitations of the algorithm we have created. What could we do differently to fix the issue. Consider what happens with the system

\begin{align}
x -2y &= 2\\
2x - 4y &= 4\\
\end{align}

Some of the limitation of our algorithm is that if you get all zero in the bottom it breaks. Another limitation in my algorthm is round off error that can happen. The thing that we can do to try and fix these issues are if function for the all zero promblem.  Early this week we tried creating a if function for all zero problem but we couldnt get it to work so we left it out. What happend when you plug in 
\begin{align}
x -2y &= 2\\
2x - 4y &= 4\\
\end{align}
Is that bottom row becomes all zero and crashes the system. This system has INF solution because it is the same line!